### ISSUE TITLE
A processor with SpEL expression fails to run

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#773] opened 2018-05-06 19:27 UTC
As a user, I'm attempting to deploy the attached stream from Flo; though the deployment is successful, the SpEL parsing for the "language" fails at runtime. This works when deployed from Shell.

> tweets = twitterstream --consumer-key= --consumer-secret= --access-token= --access-token-secret= | filter --expression=#jsonPath(payload,'$.lang')=='en' | twitter-sentiment --vocabulary=http://dl.bintray.com/big-data/generic/vocab.csv --model-fetch=output/Softmax --model=http://dl.bintray.com/big-data/generic/minimal_graph.proto | field-value-counter --field-name=sentiment --name=sentiment

_(removed creds intentionally)_

Error: (from `filter` processor)
```
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.lang.Boolean] for value 'ko'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value 'ko'
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:43)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:203)
	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:67)
	at org.springframework.expression.common.ExpressionUtils.convertTypedValue(ExpressionUtils.java:53)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:235)
	at org.springframework.cloud.stream.app.filter.processor.FilterProcessorConfiguration.filter(FilterProcessorConfiguration.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:117)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:103)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:50)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:348)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:132)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:360)
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:169)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:319)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:155)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:93)
	... 41 more
Caused by: java.lang.IllegalArgumentException: Invalid boolean value 'ko'
	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:63)
	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:31)
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:386)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:37)
	... 61 more
```

**NOTE:**
The same stream definition _works_ when deployed from Shell!

**Comment by ilayaperumalg** [comment] 2018-05-07 04:40
@sabbyanandan I just tried this stream from the UI and it looks ok when deployed. 

If you are running locally, can you see what is the DSL being used when deploying the stream from the UI?

**Comment by sabbyanandan** [comment] 2018-05-09 01:12
I consistently see it. I just tried the following on 1.5 RC and I see the same error on `filter` processor.

> tweets = twitterstream --consumer-key= --consumer-secret= --access-token= --access-token-secret= | filter --expression=#jsonPath(payload,'$.lang')=='en' | twitter-sentiment --vocabulary=http://dl.bintray.com/big-data/generic/vocab.csv --model-fetch=output/Softmax --model=http://dl.bintray.com/big-data/generic/minimal_graph.proto | field-value-counter --field-name=sentiment --name=sentiment

You don't even need the sentiment processor; just with `twitterstream | filter | log`, you should be able to reproduce it.

**Comment by sabbyanandan** [comment] 2018-05-09 01:14
Also, I'm using the Celsius.SR1 on Kafka. The same combination continues to work when deployed from Shell.

**Comment by tzolov** [comment] 2018-05-09 06:03
@sabbyanandan,  is this skipper mode?

**Comment by tzolov** [comment] 2018-05-09 06:25
FYI, i tested ( a week ago) the same stream usecase using SCDF 1.5.0.M1 (classic mode + rabbit) and the latest (Darwin RC1) SCSt apps starters.  Here is the gist: https://gist.github.com/tzolov/ce73902f7d2db897caeddace3c8e8625
1. I had to rebuild/re-register the `twitter-sentiment` because of the byte array content-type issue. 
2.  Because of a SI "issue" (inherited form the JSON lib),  the SpEL expressions can only be of `String`  and *not* `byte[]`  type. But twitterstream produces byte[] payload and the workaround is to convert it to string (e.g. new String(payload)).  In turn to escape the space in the new string expression i had to add outer quotes and escape (e.g. double quote ) the inner quotes:
```
stream create --name tweets --definition "twitterstream --access-token-secret= --access-token= --consumer-secret= --consumer-key= --track=java --stream-type=filter | filter --expression='#jsonPath(new String(payload),''$.lang'')==''en'' ' | twitter-sentiment --vocabulary='http://dl.bintray.com/big-data/generic/vocab.csv' --output-name='output/Softmax' --model-fetch='output/Softmax' --model='http://dl.bintray.com/big-data/generic/minimal_graph.proto' | log"
```

**Comment by ilayaperumalg** [comment] 2018-05-09 08:42
I am able to see the issue now (though intermittently) and this is due the Stream Deploy - Edit changes.

The root cause of the issue is the strategy we use to pass all the `application` properties from even the stream definition DSL as `deployment` properties when deploying the stream. and, during this process some of the property values are incorrectly updated. 

For instance, the SpEL expression in the `filter` app is modified incorrectly as `#jsonPath(payload,'$.lang')` instead of `#jsonPath(payload,'$.lang')=='en'`.

I see one more issue with this. All the masked sensitive properties are passed as `****` from the UI when deploying the stream.

Assigning this to @oodamien to have a look at the Stream deploy page.

I am also trying to debug why this happens inconsistently.

**Comment by tzolov** [comment] 2018-05-09 10:02
@sabbyanandan @ilayaperumalg i am afraid that the problem is bigger (not only UI) and rooted to the ArgumentSanitizer. 
Please try to run `stream list` after the deployment. For me it blows inside the sanitizer

**Comment by ilayaperumalg** [comment] 2018-05-09 10:05
@tzolov Are you on the latest master or 1.5.0.RC1? It looks ok to me.

 We fixed an issue with the `stream list` related to Argument Sanitizer: https://github.com/spring-cloud/spring-cloud-dataflow/commit/7831f6b31b3ecb3cb4c572def8e2305d0bf44745

**Comment by ilayaperumalg** [comment] 2018-05-09 10:08
@oodamien Thanks for fixing the SpEL expression properties issue. Created https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/780 on the sensitive properties issue mentioned above.

**Comment by tzolov** [comment] 2018-05-09 10:32
@ilayaperumalg yes i've pulled latest changes including SCDF#2185. 
Please try to create this stream from the shell or the ui:
```
twitterstream --twitter.stream.stream-type=filter --twitter.stream.track=java --twitter.credentials.access-token-secret= --twitter.credentials.consumer-secret= --twitter.credentials.consumer-key=  --twitter.credentials.access-token= | filter --filter.expression=#jsonPath(payload,'$.lang')=='en' | log
```

**Closed** 2018-05-09 11:36 UTC
Labels: bug, in pr
