### ISSUE TITLE
UI for the jobs tab

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow-ui#918] opened 2018-09-25 09:44 UTC
Currently the jobs tab simply displays all the jobs and their statuses. I have more than 100 jobs hence it becomes difficult to track the ones which failed. Spring batch admin had a feature where we can look at a particular job and get its executions. Also, I wanted to request for a feature in which we can sort the jobs or filter the ones which have recently failed so i can restart them.

**Comment by sabbyanandan** [comment] 2018-10-08 21:28
Thank you for the feedback, but it seems like a duplicate of://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/920. 

We will revisit this enhancement in 2.0 line of SCDF.

**Closed by sabbyanandan** 2018-10-08 21:28 UTC
