### ISSUE TITLE
Unregister multiple apps doesn't clear button state

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#288] opened 2017-07-26 15:54 UTC
After unregistring apps via tri-state-button, it still shows to unregister same count of apps.
![ui-unregister-multiple-apps](https://user-images.githubusercontent.com/50398/28630762-138c59ec-7223-11e7-91d2-f5b87bbe4e2b.png)

**Comment by cppwfs** [comment] 2017-07-26 15:57
Duplicate of https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/282

**Closed by cppwfs** 2017-07-26 15:57 UTC
Labels: angular4-upgrade, bug, ready
