### ISSUE TITLE
Spring Boot 3 / Batch 5: Job execution is empty although shown in DB

### ISSUE THREAD

**Issue by vauvenal5** [spring-cloud/spring-cloud-dataflow-ui#1946] opened 2023-08-25 09:21 UTC
Working with SCDF 2.11-RC1 we successfully run a Boot3/Batch5 job and see the job steps in the DB. However, in the SCDF UI the Job executions tab stays empty. I guess it is reading only the Boot2 tables and not the Boot3 tables.

Is there a config which we missed to switch or is this a bug?

**Comment by onobc** [comment] 2023-08-30 04:07
Hi @vauvenal5 ,
What your Boot3/Batch5 job registered as a Boot 3.x task app? Do you mind sharing the contents of http://<server>:<port>/dashboard/index.html#/apps/task/<your-app-name-goes-here> ?

**Comment by vauvenal5** [comment] 2023-08-30 05:41
Here the Spring Dataflow UI:
![image](https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/1935503/fcf58f61-da4c-40b9-87b0-24aaa2c12b41)
![image](https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/1935503/85692f07-4e37-4e19-984e-bc35a79344f2)
![image](https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/1935503/e6019cb0-790e-4e9b-811b-a01cf908f195)

And here our DB:
![image](https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/1935503/e930e6fc-cc05-43f6-afbb-4e66ef485625)
![image](https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/1935503/390d0e08-916f-4265-be61-346d931dfd34)

**Comment by onobc** [comment] 2023-08-30 20:11
Awesome detail @vauvenal5 !

> I guess it is reading only the Boot2 tables and not the Boot3 tables. Is there a config which we missed to switch or is this a bug?

We read from either the 2x or 3x tables based on the app type (and here it is correctly registered as the 3x app). Also, the fact that the data landed in the 3x tables is another indicator it knows it is in a 3x env. I notice that the batch job failed and I wonder if there is an issue related to rendering in that case. 

We will take a deeper look on our side and see if we can reproduce etc.. 

Thanks

**Comment by onobc** [comment] 2023-09-12 14:50
@vauvenal5 would you mind sharing the contents of the following views and tables in the DB for this failed case? 

- `AGGREGATE_TASK_EXECUTION, TASK_EXECUTION, BOOT3_TASK_EXECUTION`
- `AGGREGATE_JOB_EXECUTION, BATCH_JOB_EXECUTION, BOOT3_BATCH_JOB_EXECUTION`

Thanks

**Comment by cppwfs** [comment] 2023-09-12 21:43
Also provide the BOOT3_TASK_TASK_BATCH table as well.

**Comment by cppwfs** [comment] 2023-09-13 16:04
We were unable to reproduce this issue.   If you can provide a sample task/batch application that exhibits this behavior with SCDF please add it or the project location to the comments.  At which time we'll reopen the issue.  
Thank you!

**Closed by cppwfs** 2023-09-13 16:04 UTC
Labels: status/need-triage

**Comment by vauvenal5** [comment] 2023-10-05 16:57
Maybe a short information for anyone looking latter at this. The issue was on our side, we were not properly taking arguments passed from SCDF and this lead to the issues in our case.
