### ISSUE TITLE
Error when I click view log button in task execution screen in Spring CLoud Dataflow Dashboard

### ISSUE THREAD

**Issue by mapozo** [spring-cloud/spring-cloud-dataflow-ui#1553] opened 2020-09-16 10:04 UTC
I have set up Spring Cloud Dataflow 2.7.0-SNAPSHOT to run spring batch's tasks in Openshift. I registered an app, using a valid docker path, and created a task using this app.

When I execute the task from SCDF dashboard using an specific platform from the drop-down , the task gets properly executed on Openshift. When I access the task execution screen, I click the button "View Logs", and I get the following error on screen: "Log could not be retrieved. Verify that deployments are still available."

In SCDF log file I get: 2020-09-15 14:12:16.546 WARN 7 --- [nio-9376-exec-1] .s.c.d.s.s.i.DefaultTaskExecutionService : Failed to retrieve the log, returning verification message.

java.lang.IllegalStateException: No Launcher found for the platform named 'default'. Available platform names are [platform-test, platform-dev] at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.findTaskLauncher(DefaultTaskExecutionService.java:683) at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.getLog(DefaultTaskExecutionService.java:605)

I have seen that REST API endpoint(http://localhost:9393/tasks/logs/<external_exec_id>?platformName=platform-dev) to get the log works properly, but, from dashboard we are invoking http://localhost:9393/tasks/logs/<external_exec_id>, not including platformName.

could you check it, please?

original link on stackoverflow:
https://stackoverflow.com/questions/63904262/error-when-i-click-view-log-button-in-task-execution-screen-in-spring-cloud-data

Thanks and regards!

**Comment by cppwfs** [comment] 2020-09-16 12:24
Thank you for the issue, however it is a duplicate of https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1551

**Closed by cppwfs** 2020-09-16 12:24 UTC
