### ISSUE TITLE
Validation on Task builder prevents mixing identifying and non identifying params 

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1685] opened 2021-03-12 12:37 UTC
The builder marks the arguments as invalid if I mix parameters with `--` and without `--`
![image](https://user-images.githubusercontent.com/695673/110940616-3314ac00-8305-11eb-82b4-800139d22f68.png)

**Comment by hpoettker** [comment] 2021-03-24 09:42
The problem is independent of whether parameters are identifying or not. Currently, every argument except the first is validated as if it where a property. As it's rare that arguments pass that validation, practically every argument except the first is marked as invalid.

**Closed** 2021-05-17 12:46 UTC
Labels: status/need-triage, type/bug
