### ISSUE TITLE
Task status shown as complete even when the batch job fails

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow-ui#917] opened 2018-09-24 12:16 UTC
I have a task with 2 batch jobs, both jobs run but one of them fails. The status of the particular task is still shown as complete. Is this a bug or is it meant to be?

**Comment by cppwfs** [comment] 2018-09-24 15:10
Actually yes.  A failure in a spring batch job does not mean that the application that ran it fail.  This is because spring batch technically handled the problem and recorded the failure.   With spring batch, you can always restart a failed job and it will pick up where it left off (keep in mind your code has to be written to support a restart).   
If you want spring task app to return an exit code other than zero (i.e. fail) if the batch job fails you will need to set the `spring.cloud.task.batch.failOnJobFailure` property to true.

**Comment by siddhantsorann** [comment] 2018-09-25 05:46
Hey, thanks for the clarification. But where do I set this property exactly?

**Comment by cppwfs** [comment] 2018-09-25 16:17
It can be set as an app property when you launch your task.

**Comment by siddhantsorann** [comment] 2018-09-26 08:39
Hey, so i sent it as a task argument from the UI, --spring.cloud.task.batch.failOnJobFailure=true but i get the following error: (Also, I couldnt find this property when in the UI i try to find it in the properties list)
```
o.s.boot.SpringApplication               : Application startup failed

java.lang.AbstractMethodError: null
	at org.springframework.beans.factory.support.AbstractBeanFactory.isSingleton(AbstractBeanFactory.java:402) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:447) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:415) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.getLifecycleBeans(DefaultLifecycleProcessor.java:273) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:131) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:852) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.2
```.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at com.mediaiq.appnexus.batch.AppnexusBatchServiceApplication.main(AppnexusBatchServiceApplication.java:53) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [aiq-appnexus-batch-service-3.23.1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [aiq-appnexus-batch-service-3.23.1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [aiq-appnexus-batch-service-3.23.1.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [aiq-appnexus-batch-service-3.23.1.jar:na]

**Comment by siddhantsorann** [comment] 2018-09-27 07:08
So the sample batch worked for me too. But when i changed the spring boot version to 1.3.2 from 2.0.0 it started giving me the above error.

**Comment by cppwfs** [comment] 2018-09-27 11:56
Hmm...   I also ran a set of Batch/Task Apps using 2.0.0.  and still not seeing the problem.   Can you provide me a sample application that reproduces this problem?

**Comment by siddhantsorann** [comment] 2018-09-28 06:09
Hey, Issue is when i run it with spring boot 1.3.2

**Comment by cppwfs** [comment] 2018-10-01 13:08
If you are writing a task using Spring Cloud Task 2.0, you must use Spring Boot 2.0.    Spring Cloud Data Flow can launch Spring Boot 2.0 task/apps.

**Comment by mrbq** [comment] 2018-10-01 14:03
> If you are writing a task using Spring Cloud Task 2.0, you must use Spring Boot 2.0. Spring Cloud Data Flow can launch Spring Boot 2.0 task/apps.

So I need to use spring cloud task 1.2.3.RELEASE instead?

**Comment by cppwfs** [comment] 2018-10-01 14:10
If you want to use boot 1.5.x for your task application.  Then yes.

**Comment by sabbyanandan** [comment] 2018-10-01 15:14
@siddhantsorann: It appears you're on a very old Spring Boot (1.3.2) release. Even the 1.0 GA release of Spring Cloud Task (SCT) and Spring Cloud Data Flow builds on top of a much latest versions of Spring Boot. In other words, we have never validated the feature capabilities on that old stack, so please upgrade to latest GA version of 1.5.x or 2.0.x for custom SCT apps.

@mrbq: As Glenn pointed out, SCT 2.0.x _requires_ Spring Boot 2.0.x and likewise, SCT 1.2.x builds on Spring Boot 1.5.x as the foundation. Please make sure you're using the compatible versions. If you continue to see issues, it'd be good if you can open an issue with a reproducible sample app in [SCDF core](https://github.com/spring-cloud/spring-cloud-dataflow/issues). 

I'm closing this since we cannot reproduce it on our end so far and also, there's a duplicate thread in [StackOverflow](https://stackoverflow.com/questions/52531263/spring-cloud-task-status-shown-as-complete-even-when-the-batch-job-fails).

**Closed by sabbyanandan** 2018-10-01 15:14 UTC
Labels: question

**Comment by mrbq** [comment] 2018-10-02 14:08
Hi, 

Just for the record, when downgrading to Spring Cloud Task 1.2.3.RELEASE I found some issues. First of all, the database intializer of the version 1.2.3.RELEASE is not compatible with more than one datasource so I had to write an utility to get the datasource configured in the TaskConfigurer and then call the TaskRepositoryInitializer (see [https://gist.github.com/mrbq/f746201a80a2490ff54e160fdece06b4](url)). 

Apart from that, the default job command line runner used by Spring Cloud Task 1.2.3.RELEASE does not support the flag "failOnJobFailure" because this is a feature only supported by Spring Cloud Task 2.0.0.RELEASE onwards. So I included some of the behaviour of the 2.0.0 command line runner in a custom command line runner: [https://gist.github.com/mrbq/e6fc7b6c7a0fd1efc6374dc4f4645bf6](url). Note that only the "execute" method was modified.

Best regards.

**Comment by siddhantsorann** [comment] 2018-10-03 05:48
@mrbq Hey, thanks for the info. So are you saying that with this custom command line runner i can implement the failOnJobFailure property with spring boot 1.2.3?

**Comment by mrbq** [comment] 2018-10-03 06:00
> 
> 
> @mrbq Hey, thanks for the info. So are you saying that with this custom command line runner i can implement the failOnJobFailure property with spring boot 1.2.3?

Yes, I had the same problem with the exit code and what I have implemented is a configuration class that has a condition on the property _failOnJobFailure_, if its value is true then it creates an instance of the [TaskJobCommandLineRunner](https://gist.github.com/mrbq/e6fc7b6c7a0fd1efc6374dc4f4645bf6). 

Best regards.

**Comment by siddhantsorann** [comment] 2018-10-03 06:04
@mrbq Can you please help me out as to how I can add this custom command line runner in my project and use it? Thanks a lot!

**Comment by mrbq** [comment] 2018-10-03 06:18
> 
> 
> @mrbq Can you please help me out as to how I can add this custom command line runner in my project and use it? Thanks a lot!

Yes I can help you out, you can find me on gitter (same username)

**Comment by Manu10744** [comment] 2023-04-12 15:26
Any idea why this property `--spring.cloud.task.batch.failOnJobFailure=true` clashes with `EnableBatchProcessing(modular=true)`? After adding this property my task fails with the exception

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'transactionManager', defined in class path resource [org/springframework/cloud/task/configuration/SimpleTaskAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/batch/core/configuration/annotation/ModularBatchConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

```
